image: thyrlian/android-sdk

stages:
  - build
  - test

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - app/build/outputs/apk/release/*.apk
      - app/build/outputs/apk/debug/*.apk
  only:
    - master

unit_test:
  stage: test
  script:
    - ./gradlew check

device_test:
  stage: test
  script: 
    - echo "no" | avdmanager create avd -n test -k "system-images;android-25;google_apis;armeabi-v7a"
    - emulator64-arm -avd test -noaudio -no-boot-anim -gpu offscreen
    - ./gradlew connectedAndroidTest
